### ISSUE TITLE
Using lists of numpy arrays is broken

### ISSUE THREAD

**Issue by derhintze** [pog87/PtitPrince#23]
Trying to get a simple raincloud plot with toy data, generated synthetically:

```python
>>> import numpy as np
>>> from ptitprince import PtitPrince as pt
>>> data = np.random.randn(1000)
>>> ax = pt.RainCloud(y=data, orient="ver")  # a single 1D vector raincloud plot works
>>> data = [np.random.randn(300), np.random.randn(300) + 1]
>>> ax = pt.RainCloud(y=data, orient="ver")  # trying list input as in jupyter notebook
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 762, in RainCloud
    half_violinplot(x = x, y = y, hue = hue, data = data,
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 681, in half_violinplot
    plotter = _Half_ViolinPlotter(x, y, hue, data, order, hue_order,
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 112, in __init__
    self.establish_variables(x, y, hue, data, orient, order, hue_order)
  File "my_virtual_env/lib/python3.9/site-packages/seaborn/categorical.py", line 156, in establish_variables
    orient = infer_orient(
  File "my_virtual_env/lib/python3.9/site-packages/seaborn/_core.py", line 1321, in infer_orient
    raise TypeError(nonnumeric_dv_error.format("Vertical", "y"))
TypeError: Vertical orientation requires numeric `y` variable.
>>> data = np.asarray([np.random.randn(300), np.random.randn(300) + 1])
>>> ax = pt.RainCloud(y=data, orient="ver")  # trying 2D array instead
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 779, in RainCloud
    ax =  stripplot (x = x, y = y, hue = hue, data = data, orient = orient,
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 671, in stripplot
    plotter.plot(ax, kwargs)
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 98, in plot
    self.draw_stripplot(ax, kws)
  File "my_virtual_env/lib/python3.9/site-packages/ptitprince/PtitPrince.py", line 66, in draw_stripplot
    strip_data = group_data[hue_mask]
IndexError: boolean index did not match indexed array along dimension 0; dimension is 2 but corresponding boolean dimension is 600
```

My environment:

- Python 3.9.1
- numpy 1.20.3
- Pandas 1.2.5
- Seaborn 0.11.2

**Comment by pog87** [comment]
Hi @derhintze and thanks for using RC plots.

I am afraid this is not the correct way to pass the arguments to the function, you also need to pass a categorical column. Please refer to the tutorials.
